/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.md2.ui.internal.Md2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Md2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Md2Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Md2Activator activator = Md2Activator.getInstance();
		return activator != null ? activator.getInjector(Md2Activator.ORG_XTEXT_EXAMPLE_MYDSL_MD2) : null;
	}

}
