/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl2.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class Md3ProposalProvider extends AbstractMd3ProposalProvider {
}
