/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.Md2RuntimeModule;
import org.xtext.example.mydsl.Md2StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Md2IdeSetup extends Md2StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Md2RuntimeModule(), new Md2IdeModule()));
	}
	
}
