/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.md2.ui.internal.Md2Activator;

public class Md2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Md2Activator.getInstance().getInjector("org.xtext.example.mydsl.Md2");
	}

}
