/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl2.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.md3.ui.internal.Md3Activator;

public class Md3UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Md3Activator.getInstance().getInjector("org.xtext.example.mydsl2.Md3");
	}

}
