/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl2.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl2.parser.antlr.internal.InternalMd3Parser;
import org.xtext.example.mydsl2.services.Md3GrammarAccess;

public class Md3Parser extends AbstractAntlrParser {

	@Inject
	private Md3GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMd3Parser createParser(XtextTokenStream stream) {
		return new InternalMd3Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Md3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Md3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
