/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Md2UiModule extends AbstractMd2UiModule {

	public Md2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
