/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Md2StandaloneSetup extends Md2StandaloneSetupGenerated {

	public static void doSetup() {
		new Md2StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
