/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl2;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Md3StandaloneSetup extends Md3StandaloneSetupGenerated {

	public static void doSetup() {
		new Md3StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
