/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl2.ide;


/**
 * Use this class to register ide components.
 */
public class Md3IdeModule extends AbstractMd3IdeModule {
}
