/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl2.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl2.Md3RuntimeModule;
import org.xtext.example.mydsl2.Md3StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Md3IdeSetup extends Md3StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Md3RuntimeModule(), new Md3IdeModule()));
	}
	
}
