/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Md3UiModule extends AbstractMd3UiModule {

	public Md3UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
